project:
  type: website

website:
  title: pdf-metadata-enhancer
  favicon: _extensions/Stadt-Geschichte-Basel/sgb-theme/favicon.png
  open-graph: true
  twitter-card: true
  site-url: https://dokumentation.stadtgeschichtebasel.ch/pdf-metadata-enhancer/
  repo-url: https://github.com/Stadt-Geschichte-Basel/pdf-metadata-enhancer/
  issue-url: https://github.com/Stadt-Geschichte-Basel/pdf-metadata-enhancer/issues/new/choose
  repo-actions: [edit, issue]
  page-navigation: true
  bread-crumbs: true
  back-to-top-navigation: true
  search:
    show-item-context: true
    type: overlay
  navbar:
    logo: _extensions/Stadt-Geschichte-Basel/sgb-theme/assets/img/logo.svg
    logo-alt: 'Stadt.Geschichte.Basel Logo'
    title: pdf-metadata-enhancer
    tools:
      - icon: github
        url: https://github.com/Stadt-Geschichte-Basel/pdf-metadata-enhancer/

  sidebar:
    contents:
      - text: Home
        href: index.qmd
      - text: Changelog
        href: CHANGELOG.md
      - text: Code of Conduct
        href: CODE_OF_CONDUCT.md
      - text: Contributing
        href: CONTRIBUTING.md
      - text: License (Data)
        href: LICENSE-CCBY.md
      - text: License (Code)
        href: LICENSE-AGPL.md
      - text: Security
        href: SECURITY.md

format:
  sgb-theme-html:
    toc: true
    theme:
      - brand
      - cosmo
    code-copy: true
    code-overflow: wrap

freeze: true

editor: visual
