contact_links:
  - name: Are you looking for documentation on pdf-metadata-enhancer?
    url: https://Stadt-Geschichte-Basel.github.io/pdf-metadata-enhancer
    about: Please see the documentation for pdf-metadata-enhancer on its GitHub Pages page.
  - name: Do you want to discuss pdf-metadata-enhancer with the community?
    url: https://github.com/Stadt-Geschichte-Basel/pdf-metadata-enhancer/discussions
    about: Please see the discussions page for pdf-metadata-enhancer.
blank_issues_enabled: true
